--- 
qa: 
  show_alert_dropdown: "true"
  make_all_virtual_gifts_free: "true"
  enable_recent_albums: "false"
  enable_enhanced_footer: "false"
  show_static_message: "false"
  hide_header_ad: "true"
  gedcom_import_node_limit: 50_000
  enable_posted_documents: "true"
  enable_paypal_for_points: "true"
  promo_total_profiles: 70 million
  num_famous_profiles: "3"
  enable_paypal_for_orders: "true"
  count_popular_profiles: "true"
  show_checkout_confirmation: "true"
  enable_tree_posters: "true"
  enable_paypal_for_subscriptions: "true"
  enable_support_phone_number: "false"
  enable_google_analytics: "true"
  enable_click_logs: "false"
  display_popular_profiles: "true"
  strongmail_host: strongmail-001.geni.com
  gedcom_premium_export_node_limit: 100_000
  enable_proflowers: "true"
  enable_profile_bulk_edit_mode: "false"
  log_path_repair_errors: "true"
  hide_ads: "false"
  ezprints_partner_number: "716"
  enable_paypal: "true"
  enable_api: "true"
  enable_checkout_free: "true"
  enable_simple_privacy_explanation: "false"
development: 
  show_alert_dropdown: "true"
  make_all_virtual_gifts_free: "true"
  enable_recent_albums: "false"
  enable_enhanced_footer: "false"
  show_static_message: "false"
  hide_header_ad: "true"
  gedcom_import_node_limit: 50_000
  enable_posted_documents: "true"
  enable_paypal_for_points: "true"
  promo_total_profiles: 70 million
  num_famous_profiles: "0"
  enable_paypal_for_orders: "true"
  count_popular_profiles: "true"
  show_checkout_confirmation: "true"
  enable_tree_posters: "false"
  enable_paypal_for_subscriptions: "true"
  enable_support_phone_number: "false"
  enable_google_analytics: "false"
  enable_click_logs: "false"
  display_popular_profiles: "true"
  strongmail_host: strongmail-001.geni.com
  gedcom_premium_export_node_limit: 100_000
  enable_proflowers: "true"
  enable_profile_bulk_edit_mode: "false"
  log_path_repair_errors: "true"
  hide_ads: "false"
  ezprints_partner_number: skip
  enable_paypal: "true"
  enable_api: "true"
  enable_checkout_free: "true"
  enable_simple_privacy_explanation: "false"
production: 
  show_alert_dropdown: "true"
  make_all_virtual_gifts_free: "true"
  enable_recent_albums: "false"
  enable_enhanced_footer: "false"
  show_static_message: "false"
  hide_header_ad: "true"
  gedcom_import_node_limit: 50_000
  enable_posted_documents: "false"
  enable_paypal_for_points: "false"
  promo_total_profiles: 70 million
  num_famous_profiles: "3"
  enable_paypal_for_orders: "false"
  count_popular_profiles: "true"
  show_checkout_confirmation: "true"
  enable_tree_posters: "false"
  enable_paypal_for_subscriptions: "false"
  enable_support_phone_number: "false"
  enable_google_analytics: "true"
  enable_click_logs: "true"
  display_popular_profiles: "true"
  strongmail_host: strongmail-001.geni.com
  gedcom_premium_export_node_limit: 100_000
  enable_proflowers: "true"
  enable_profile_bulk_edit_mode: "false"
  log_path_repair_errors: "false"
  hide_ads: "false"
  ezprints_partner_number: "716"
  enable_paypal: "false"
  enable_api: "false"
  enable_checkout_free: "true"
  enable_simple_privacy_explanation: "false"
test: 
  show_alert_dropdown: ""
  make_all_virtual_gifts_free: "false"
  enable_recent_albums: "false"
  enable_enhanced_footer: "true"
  show_static_message: "false"
  hide_header_ad: "true"
  gedcom_import_node_limit: 50_000
  enable_posted_documents: "true"
  enable_paypal_for_points: "true"
  promo_total_profiles: 70 million
  num_famous_profiles: "3"
  enable_paypal_for_orders: "true"
  count_popular_profiles: "false"
  show_checkout_confirmation: "true"
  enable_tree_posters: "true"
  enable_paypal_for_subscriptions: "true"
  enable_support_phone_number: "false"
  enable_google_analytics: "false"
  enable_click_logs: "false"
  display_popular_profiles: "true"
  strongmail_host: strongmail-001.geni.com
  gedcom_premium_export_node_limit: 100_000
  enable_proflowers: "true"
  enable_profile_bulk_edit_mode: "false"
  log_path_repair_errors: "false"
  hide_ads: "false"
  ezprints_partner_number: skip
  enable_paypal: "true"
  enable_api: "true"
  enable_checkout_free: "true"
  enable_simple_privacy_explanation: "false"
staging: 
  show_alert_dropdown: "true"
  make_all_virtual_gifts_free: "true"
  enable_recent_albums: "false"
  enable_enhanced_footer: "false"
  show_static_message: "false"
  hide_header_ad: "true"
  gedcom_import_node_limit: 50_000
  enable_posted_documents: "true"
  enable_paypal_for_points: "true"
  promo_total_profiles: 70 million
  num_famous_profiles: "3"
  enable_paypal_for_orders: "true"
  count_popular_profiles: "true"
  show_checkout_confirmation: "true"
  enable_tree_posters: "false"
  enable_paypal_for_subscriptions: "true"
  enable_support_phone_number: "false"
  enable_google_analytics: "true"
  enable_click_logs: "true"
  display_popular_profiles: "true"
  strongmail_host: strongmail-001.geni.com
  gedcom_premium_export_node_limit: 100_000
  enable_proflowers: "true"
  enable_profile_bulk_edit_mode: "false"
  log_path_repair_errors: "true"
  hide_ads: "false"
  ezprints_partner_number: "716"
  enable_paypal: "true"
  enable_api: "true"
  enable_checkout_free: "true"
  enable_simple_privacy_explanation: "false"
